language: java
jdk: openjdk10
sudo: required
dist: trusty
mono: none
branches:
- only:
  - master
before_script:
- dotnet restore
script:
- java build src
notifications:
  email:
    recipients:
      - agusia031@wp.pl
    on_success: always
    on_failure: always
  slack:
    on_success: always
    on_failure: always